github actions

diff --git a/.github/workflows/moodle-ci.yml b/.github/workflows/moodle-ci.yml
--- a/.github/workflows/moodle-ci.yml
+++ b/.github/workflows/moodle-ci.yml
@@ -1,17 +1,18 @@
-name: Moodle Plugin CI
+name: Run all tests
 
+# Run this workflow every time a new commit pushed to your repository
 on: [push, pull_request]
 
 jobs:
-  test:
-    runs-on: ubuntu-18.04
-
+  setup:
+    runs-on: ubuntu-latest
     services:
       postgres:
         image: postgres:10
         env:
           POSTGRES_USER: 'postgres'
           POSTGRES_HOST_AUTH_METHOD: 'trust'
+        # Health check to wait for postgres to start.
         ports:
           - 5432:5432
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
@@ -23,86 +24,94 @@ jobs:
         ports:
           - 3306:3306
         options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
-
     strategy:
       fail-fast: false
       matrix:
-        php: ['7.4', '8.0']
-        moodle-branch: ['MOODLE_311_STABLE', 'MOODLE_400_STABLE']
-        database: [pgsql, mariadb]
-
+        php-versions: ['7.3', '8.0']
+        database: ['pgsql', 'mariadb']
     steps:
       - name: Check out repository code
         uses: actions/checkout@v2
         with:
+          # Clone in plugin subdir, so we can setup CI in default directory.
           path: plugin
 
-      - name: Setup PHP ${{ matrix.php }}
-        uses: shivammathur/setup-php@v2
+      - name: Install node
+        uses: actions/setup-node@v1
         with:
-          php-version: ${{ matrix.php }}
-          extensions: ${{ matrix.extensions }}
-          ini-values: max_input_vars=5000
-          coverage: none
+          # TODO: Check if we can support .nvmrc
+          node-version: '14.15.0'
 
-      - name: Initialise moodle-plugin-ci
+      - name: Setup PHP environment
+        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
+        with:
+          php-version: ${{ matrix.php-versions }}
+          extensions: mbstring, pgsql, mysqli
+          ini-values: max_input_vars=5000
+          tools: phpunit
+
+      - name: Deploy moodle-plugin-ci
         run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
+          # Add dirs to $PATH
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
+          # PHPUnit depends on en_AU.UTF-8 locale
           sudo locale-gen en_AU.UTF-8
-          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
-
       - name: Install moodle-plugin-ci
-        run: |
-          moodle-plugin-ci add-plugin --branch master iarenaza/moodle-filter_multilang2
-          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
+        # Need explicit IP to stop mysql client fail on attempt to use unix socket.
+        run: moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
         env:
           DB: ${{ matrix.database }}
-          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
+          # TODO: Omitted MOODLE_BRANCH results in regex failure, investigate.
+          MOODLE_BRANCH: 'master'
 
-      - name: PHP Lint
+      - name: Run phplint
         if: ${{ always() }}
         run: moodle-plugin-ci phplint
 
-      - name: PHP Copy/Paste Detector
-        continue-on-error: true # This step will show errors but will not fail
+      - name: Run phpcpd
         if: ${{ always() }}
-        run: moodle-plugin-ci phpcpd
+        run: moodle-plugin-ci phpcpd || true
 
-      - name: PHP Mess Detector
-        continue-on-error: true # This step will show errors but will not fail
+      - name: Run phpmd
         if: ${{ always() }}
         run: moodle-plugin-ci phpmd
 
-      - name: Moodle Code Checker
+      - name: Run codechecker
         if: ${{ always() }}
         run: moodle-plugin-ci codechecker
 
-      - name: Moodle PHPDoc Checker
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpdoc
-
-      - name: Validating
+      - name: Run validate
         if: ${{ always() }}
         run: moodle-plugin-ci validate
 
-      - name: Check upgrade savepoints
+      - name: Run savepoints
         if: ${{ always() }}
         run: moodle-plugin-ci savepoints
 
-      - name: Mustache Lint
+      - name: Run mustache
         if: ${{ always() }}
-        run: moodle-plugin-ci mustache
+        run: moodle-plugin-ci phpcpd || true
+        env:
+          MUSTACHE_IGNORE_NAMES: mobile_teacher_form.mustache
 
-      - name: Grunt
+      - name: Run grunt
         if: ${{ always() }}
         run: moodle-plugin-ci grunt
 
-      - name: PHPUnit tests
+      - name: Run phpdoc
         if: ${{ always() }}
-        run: moodle-plugin-ci phpunit
+        run: moodle-plugin-ci phpdoc
 
-      - name: Behat features
+      - name: Run phpunit
+        if: ${{ always() }}
+        run: | 
+             moodle-plugin-ci phpunit
+             cd moodle
+             vendor/bin/phpunit --fail-on-risky --disallow-test-output --filter tool_dataprivacy_metadata_registry_testcase
+             vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_privacy_testsuite --filter provider_testcase 
+
+      - name: Run behat
         if: ${{ always() }}
         run: moodle-plugin-ci behat --profile chrome
